### ISSUE TITLE
stack vs recursion and std::function

### ISSUE THREAD

**Issue by ibtaylor** [facontidavide/ros_type_introspection#14]
Another strange performance point (when profiling with perf) seemed to be in `buildRosFlatTypeImpl`.

Two things I would do would be to remove the usage of `std::function`
Use a stack to keep up with the tree parent (think that's all that would be needed) rather than using recursion.

I'm working on a patch, but thought I would make an issue in case I am too slow.

**Comment by facontidavide** [comment]
honestly I am not sure I agree that recursion can be avoided, nor that it will make things much faster, if not in very trivial cases. I can surely reduce identify these special cases and use them. but if you have a patch in mind, please send a PR to branch dev

**Comment by facontidavide** [comment]
Just thinking. A Low hanging fruit might be to

*) Identify those messages with all the fields equal to BuiltInType. For example Quaternion, Vector3, Header, etc. This will already reduce the number of recursions considerably.

In the past I fantasized about translating the message deserialization tree only once and build same very basic type of bytecode that describes all the steps of the deserialization, but being honest I don't think the number of users I have right now make this worth it.

Right now the best way to improve performance is avoiding as much as possible memory allocation.

So, performance wise, using a memory pool for strings/variants pair seems much more attractive.
According to Valgrind (running on the benchmark test) 72% of the time is required by ApplyNameTransform and "only" 28 by BuildRosFlatType

**Comment by facontidavide** [comment]
for you information... 
I just increased considerably the speed of ApplyNameTransform... 
https://github.com/facontidavide/ros_type_introspection/commit/f384198b0972b92a81f0f57d4d9e149065afa543

**Comment by facontidavide** [comment]
Hi @ibtaylor ,

I just want to tell you that tinkering with the code I am figuring out a lot of potential improvements, including the stack you mentioned.

The bad news is that it will mean a massive refactoring, that will take me probably few days (I can't work on this during the next weekend). So be patient. Once I have all these changes implemented, I will ask you to take a look to the new code.

**Comment by facontidavide** [comment]
I completely refactored the library (see this branch https://github.com/facontidavide/ros_type_introspection/tree/dev ).

The deserialization is dramatically faster now, even if it uses recursion. I will close this ticket

**Comment by ibtaylor** [comment]
sweet, thanks for working on it. I'll give it a try/look when I can.
