### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by teshanshanuka** [facontidavide/ros_type_introspection#23]
The ROS wiki example for creating a generic subscriber does not work for ROS Kinetic. I ended up using the example code provided in [type_introspection_tests](https://github.com/facontidavide/type_introspection_tests)
[Here's the question](https://answers.ros.org/question/301780/creating-generic-subscriber-in-kinetic-c11/) I asked on the issue before posting here. The example code on ROS Wiki needs to be updated for Kinetic (and newer I guess)

**Comment by facontidavide** [comment]
Indeed, the wiki is totally obsolete.

**Comment by facontidavide** [comment]
I will update the wiki once I come back from my holiday. Cheers

**Comment by rhaschke** [comment]
Please, update the wiki.

**Comment by facontidavide** [comment]
I am still super busy. I will try to find some mental bandwidth to deal with this issue...

**Comment by facontidavide** [comment]
Wiki updated
