### ISSUE TITLE
[SUGGESTION] Parser::applyVisitorToBuffer to support early termination

### ISSUE THREAD

**Issue by MikeChou** [facontidavide/ros_type_introspection#34]
`Parser::applyVisitorToBuffer` is an extremely useful function.
If we can control the traversal from within the visiting callback and decide whether it should continue or terminate, that will be awesome!
I think if the callback has bool as the return value, the implementation will be easy.
Any idea?

**Comment by facontidavide** [comment]
it can be surely done. Don't be afraid to send a PR yourself ;)

**Comment by facontidavide** [comment]
Hi, please take a look at changes made to fix #37 

I think it address your use case too

**Comment by MikeChou** [comment]
That's great! Thank you!

I've tested the new code on various workloads, the results are great:
workload 1:  29.3s  -> 3.3s
workload 2:  2.8s -> 0.64s
workload 3:  47.2s -> 3.0s

I'm closing this issue now.
