### ISSUE TITLE
Problems with some message types

### ISSUE THREAD

**Issue by fmorillo** [facontidavide/ros_type_introspection#35]
Hi, I have problems with some message types.

- Byte fields are interpreted as UInt8
- Duration is always 0.0
- Char fields are causing this error
```
terminate called after throwing an instance of 'std::runtime_error'
what():  unsupported builtin type value
```

I used the generic_subscriber code and tested it on ros melodic with the packaged version 1.3.1-0bionic.20190325.150517 and version 1.4.0 from github.

**Comment by facontidavide** [comment]
I want to address this, but I need more instructions to reproduce the issue.

Which messages are you subscribing to?

**Comment by fmorillo** [comment]
I basically used the publisher example code from ros.

```
#include "ros/ros.h"
#include "std_msgs/Byte.h"
#include "std_msgs/Char.h"
#include "std_msgs/Duration.h"

int main(int argc, char **argv)
{
  ros::init(argc, argv, "talker");

  ros::NodeHandle n;

  ros::Publisher chatter_pub_byte = n.advertise<std_msgs::Byte>("/chatter/byte", 1000);
  ros::Publisher chatter_pub_char = n.advertise<std_msgs::Char>("/chatter/char", 1000);
  ros::Publisher chatter_pub_dura = n.advertise<std_msgs::Duration>("/chatter/dura", 1000);

  ros::Rate loop_rate(10);

  int count = 0;
  while (ros::ok())
  {
    std_msgs::Byte msg_byte;
    std_msgs::Char msg_char;
    std_msgs::Duration msg_dura;

    msg_byte.data = 128;
    msg_char.data = 'a';
    msg_dura.data == ros::Duration(24*60*60);

    chatter_pub_byte.publish(msg_byte);
    chatter_pub_char.publish(msg_char);
    chatter_pub_dura.publish(msg_dura);

    ros::spinOnce();

    loop_rate.sleep();
    ++count;
  }

  return 0;
}
```

**Comment by facontidavide** [comment]
Hi,

In order:

- There is no way I can easily solve the problem with BYTE, since in C++ that type does not exist. 
- Duration seems to be deserialized just fine. There is a typo in your code (==):
 
         msg_dura.data == ros::Duration(24*60*60);

- Fixed the exception, thanks!

**Comment by fmorillo** [comment]
Thanks
