### ISSUE TITLE
multiple definitions

### ISSUE THREAD

**Issue by ibtaylor** [facontidavide/ros_type_introspection#4]
Non-templated methods in `shape_shifter.hpp` should be marked inline or moved to a module, otherwise, can result in multiple definitions if included by multiple files in a single project.

# Methods:
https://github.com/facontidavide/ros_type_introspection/blob/c479384b2be71a738056c5182515446ea76235c2/include/ros_type_introspection/shape_shifter.hpp#L258
https://github.com/facontidavide/ros_type_introspection/blob/c479384b2be71a738056c5182515446ea76235c2/include/ros_type_introspection/shape_shifter.hpp#L265
https://github.com/facontidavide/ros_type_introspection/blob/c479384b2be71a738056c5182515446ea76235c2/include/ros_type_introspection/shape_shifter.hpp#L220
https://github.com/facontidavide/ros_type_introspection/blob/c479384b2be71a738056c5182515446ea76235c2/include/ros_type_introspection/shape_shifter.hpp#L224
https://github.com/facontidavide/ros_type_introspection/blob/c479384b2be71a738056c5182515446ea76235c2/include/ros_type_introspection/shape_shifter.hpp#L271
https://github.com/facontidavide/ros_type_introspection/blob/c479384b2be71a738056c5182515446ea76235c2/include/ros_type_introspection/shape_shifter.hpp#L274
https://github.com/facontidavide/ros_type_introspection/blob/c479384b2be71a738056c5182515446ea76235c2/include/ros_type_introspection/shape_shifter.hpp#L277
https://github.com/facontidavide/ros_type_introspection/blob/c479384b2be71a738056c5182515446ea76235c2/include/ros_type_introspection/shape_shifter.hpp#L280
https://github.com/facontidavide/ros_type_introspection/blob/c479384b2be71a738056c5182515446ea76235c2/include/ros_type_introspection/shape_shifter.hpp#L289

**Comment by facontidavide** [comment]
Thanks, will fix it soon

**Comment by facontidavide** [comment]
thanks for reporting
