### ISSUE TITLE
File to message in c++

### ISSUE THREAD

**Issue by ahoarau** [facontidavide/ros_type_introspection#47]
Hi, 
I just came across this repo, great stuff !
Is there any way this can be used to write a function `fileToMsg`, that would basically do in c++ what 
`rostopic pub /topic type_of/msg -f  /to/file.yml` does ?

**Comment by facontidavide** [comment]
If I understand you correctly, no. 

This library can be used to handle messages from the subscriber side, not the publisher once

**Comment by facontidavide** [comment]
It MIGHT be expended to generate messages also, but this is not its purpose and I don't have time to do it. Pull Requests welcome

**Comment by StefanFabian** [comment]
I hope @facontidavide doesn't mind my shameless self-promotion but this is exactly one of the intended use cases of [ros_babel_fish](https://github.com/StefanFabian/ros_babel_fish).
For example, it is used by [qml_ros_plugin](https://github.com/StefanFabian/qml_ros_plugin) which also contains code for filling messages from a variant map similar to your described use case.
