### ISSUE TITLE
libraries shouldn't write to stdout

### ISSUE THREAD

**Issue by ibtaylor** [facontidavide/ros_type_introspection#9]
https://github.com/facontidavide/ros_type_introspection/blob/81fd04147547e7c3ea74ff18738475dea243588e/src/deserializer.cpp#L163-L166

`stderr` would be better, but I don't want to be forced to see that either.

If this is about the buffer being too small and so it only partially parsed, that seems like possibly desirable behavior, so a warning is kind of annoying.
Maybe it would be better to return the required array_size instead? Possibly return bool regarding whether it was completely processed or not.
```
buildRosFlatType(...., array_size, &required_array_size);
// at least the user can control the output now
LOG_IF(WARNING, required_array_size > array_size) << "buffer too small, results will be truncated";
```

For instance, I'm mostly interested in only parsing the `Header` and not the entire message.

**Comment by facontidavide** [comment]
I agree with you. 
A possible solution is that we add one more argument to that function as std::ostream

std::ostream might output to null, std::cout, std::cerr or a std::string, so the user can choose.

Does it make sense in your opinion?

**Comment by facontidavide** [comment]
Take a look to this change. Does it make sense in your opinion? 

https://github.com/facontidavide/ros_type_introspection/commit/0425418fd25e17950b3d316d160c689a1e4624a0

**Comment by facontidavide** [comment]
> For instance, I'm mostly interested in only parsing the Header and not the entire message.

I would say that there is no way to do this. You should implement your own version of buildRosFlatType to do that

**Comment by ibtaylor** [comment]
I'm not sure yet. Can you explain the reason for `max_array_size`? Is it intended to purposefully ignore certain large arrays or something?

**Comment by facontidavide** [comment]
Exactly. The main reasoning is that the key/value storage will create a pair for each BuiltIn element.
if someone pass an Image with 1M pixels, the result would be 1M key-value pairs.

Most of the time you want to ignore this very large vectors. You can also use an arbitrarily large number, of course.

if you want to SAVE only a part of the message, for example the Header, you can actually do it, but you need to implement a recursive function very similar to buildRosFlatType.

**Comment by facontidavide** [comment]
I introduced a solution in the PR 11

https://github.com/facontidavide/ros_type_introspection/pull/11/commits/055e57912f3ad36b0e619d8690a16c4959fa017b
